workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      java: 17
    triggering:
      events:
        - push
    scripts:
      - name: Build APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
